### ISSUE TITLE
Oney3x4x : component way too long

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#124]
**Is your feature request related to a problem? Please describe.**
Merchant wants to use Oney, however when it's displayed on the checkout page the component is way too long, see screenshot : 
![image002](https://user-images.githubusercontent.com/68015043/95303634-baa44d80-0883-11eb-8fdc-6bd4aeb6d84b.png)

**Describe the solution you'd like**
Best solution would to be able to hide the fields + prefill as many fields as possible
Maybe merging oney3x and oney4x in the same component.. ? Just an idea.

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

The personal details and address are necessary for Oney and unfortunately we cannot show only a couple of fields but we need to show the complete section even if we need only 1 field. This could be a new feature in the checkout component so we can hide single fields and not just sections.

In 1.7 we already prefill the fields (where we have the data) but in 1.6 these are not provided to the frontend so we only prefill the address which we already have.

The 3x and 4x are different payment methods so I don't think it is possible to merge them but please follow up with checkout about this maybe they can provide us some improvements in the future.

I will close this ticket now because we cannot make it shorter now, but as soon as it is possible we are going to roll out an update for that.

Best,
Attila
Adyen
