### ISSUE TITLE
[PW-3316] Incoherence between order status from notifications system and payment response handling

### ISSUE THREAD

**Issue by SammyCOLIN** [Adyen/adyen-prestashop#130]
**Description**
When an order is created with a Adyen payment, the order status is "payement accepted".
If an error has occured during the payment, for example "authentication failed (3D-secure)", but the payment is OK after the second attempt, we receive 2 notifications : one AUTHORISATION with **success FALSE** and another AUTHORISATION with **success TRUE**. So the Notification system (NotificationProcessor) move the order from "Payment accepted" to "Canceled" (first notification) and then from "Canceled" to "Payment accepted" (second notification). Consequently the customer receive one mail with "order OK" (when the order is created) and another with "order canceled" (when the first success false notification is processed).

**To Reproduce**
1. Create an order
2. Select Adyen payment method
3. 1st attempt : make an error during the 3D secure check (example : wrong code)
4. 2nd attempt : make a success payment
5. Redirection on the seller site : order OK (payment OK)
6. We receive a mail : order ok
7. 1 minute after we receive another mail : order canceled (first notif processed, cron job configured to each minute).

**Expected behavior**
Why the order is not set to status "Waiting payment" after the payment in order to let the notification system to set canceled/payment ok ?

**Screenshots**
Prestashop back-office
![2020-10-20_15h26_21](https://user-images.githubusercontent.com/73232938/96721794-ec053900-13ac-11eb-8a7e-08fb5b1e58df.png)

Notifications received (database)
![2020-10-20_15h29_17](https://user-images.githubusercontent.com/73232938/96721818-f3c4dd80-13ac-11eb-8c39-39983321e5ed.png)

**Context**

- Adyen module 2.1.7

- Prestashop 1.6.1.20

**Comment by cyattilakiss** [comment]
Hi @SammyCOLIN ,

Thank you for raising the issue. 
Indeed this happens sometimes that you receive a success = false and a success = true AUTHORISATION notification after each other. This happens when the issuer detects a 3DS1 failure first - like closing and reopening the mobile app. Unfortunately the notifications we cannot fix because it's something that the issuer sends to Adyen and Adyen forwards it to the plugin. What we can do though is not to change the order status when the authorisation success = false notification arrives because until then we already know that the payment is authorised therefore the notification can be ignored an the customer won't get an update about that this way.

We are going to investigate the above fix and get back to you soon.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @SammyCOLIN ,

We are still investigating if the proposed solution can work for all the test cases we have. We have already updated the plan with the OFFER_CLOSED notifications as well which can cause the same inconvenience for the customers.
I will keep you updated.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @SammyCOLIN ,

The proposed solution has been released in the 3.3.0.
I will close this issue but feel free to reopen it in case you have any extra comment on this.

Best,
Attila
Adyen
