### ISSUE TITLE
Shipping fees are refunded twice

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#147]
**Describe the bug**
When an order with shipping fees is refunded, those fees are refunded twice.

Example : 1319056392467061

![image001-1](https://user-images.githubusercontent.com/68015043/104726741-705d2300-5734-11eb-9006-6e1bb6abc9a1.png)
See the lines before totals: 
Réductions = discount (not relevant here)
Livraison = shipping fees. (7,5EUR)
Total amount is 47,49EUR **with shipping fees included**

See logs attached, we send a refund request (4716101020123117) for 54,99EUR (which is = 47,49 + 7,5), obviously we reject it as the amount is bigger than the original payment. 
[extractLogs.log](https://github.com/Adyen/adyen-prestashop/files/5820429/extractLogs.log)

**Comment by Morerice** [comment]
Hi @YanP-Adyen 

The issue occurred because we are currently adding the shipping amount to the credit slip whenever this is set, as can be seen here: https://github.com/Adyen/adyen-prestashop/blob/c4a20eb0b15445100fdcef1c5561307eb451a75c/service/modification/Refund.php#L91

Hence in this specific case the merchant specified the refund value to be **47,49EUR** in total, but because of this clause, the shipping cost was also automatically added to it, resulting in **54,99EUR**

Best regards,
Jeantwan

This should be fixed by checking the **shipping_cost** value in the OrderSlip entity. This value will be set whenever the merchant selects the option to also refund the shipping amount.
