### ISSUE TITLE
javascript error at Checkout: paymentMethodsResponse was provided but of an incorrect type

### ISSUE THREAD

**Issue by minhtu0405** [Adyen/adyen-prestashop#225]
**Enviroment:** Prestashop Version 1.7.5.1

**Step to reproduce:**

Add product to basket, go to basket page.
Go to Checkout Page this javascript happen at Console:

Uncaught Error: paymentMethodsResponse was provided but of an incorrect type (should be an object but a string was provided).Try JSON.parse("{...}") your paymentMethodsResponse.
    at bottom-bfbaa7781.js:289
    at new e (bottom-bfbaa7781.js:289)
    at t.setOptions (bottom-bfbaa7781.js:289)
    at t.e (bottom-bfbaa7781.js:289)
    at new t (bottom-bfbaa7781.js:289)
    at renderPaymentMethods (bottom-bfbaa7781.js:347)
    at HTMLDocument.<anonymous> (bottom-bfbaa7781.js:340)
    at u (core1.js:35)
    at Object.fireWith [as resolveWith] (core1.js:35)
    at Function.ready (core1.js:35)

at the following code:

componentButtonPaymentMethods=paymentMethodsWithPayButtonFromComponent;renderPaymentMethods();if(!IS_PRESTA_SHOP_16){setupPaymentMethods17()}

**-> Result:** No Adyen Payment methods are showed.

**Comment by cyattilakiss** [comment]
Hi @minhtu0405 ,

Sorry for the slow response. My assumption would be that something is going wrong with the paymentMethods API request. Could you please check the logs and send it over to our support team after you are able to reproduce it?
(If I understand it correctly you are able to reproduce it every time when going to the checkout)

I've actually already seen this issue a couple of times happening and the solution was almost always regenerating the API keys and cleaning the cache in Prestashop admin. The other issue was that the hooks were not installed correctly and a plugin reinstall or checking the custom theme template solved the issue.

Please let me know if it helped, otherwise just [contact support ](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420)and if needed they are going to reach out to us directly.

Best,
Attila
Adyen

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x Prestashop integration has received a full overhaul. From October 1st 2023, we will offer a full featured, new integration that has been built from scratch. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
