### ISSUE TITLE
Order confirmation email is not sent for some payment methods

### ISSUE THREAD

**Issue by ukasiu** [Adyen/adyen-prestashop#227]
**Describe the bug**

I found out that email confirmation email (order_conf) is sent for card payments but not for blik and dotpay

**Expected behavior**
order confirmation email is sent regardless of payment method

**Comment by Morerice** [comment]
Hi @ukasiu 

Thanks for raising this issue. Could you please specify the prestashop version and the adyen module version you're currently using?

Best Regards,
Jean
Adyen

**Comment by ukasiu** [comment]
Hi @Morerice,

PrestaShop: 1.7.7.7
Adyen Module: 3.7.1

Best,
Łukasz

**Comment by ukasiu** [comment]
@Morerice I checked again today and it actually works with BLIK, but doesn't work with DotPay (and also BLIK via DotPay).

**Comment by Morerice** [comment]
Hi @ukasiu 

Apologies for my late reply. We have created an internal ticket to further investigate this DotPay issue.
At first glance this seems something related to the `adyenofficial::hookActionEmailSendBefore` function, since this function is used to block the `order_conf` email in some cases.

Best regards,
Jean
Adyen

**Comment by ukasiu** [comment]
Hi @Morerice ,

it is correct not to send this email immediately, as DotPay payments take some time to complete, but they should be send later when payment is confirmed (by redirect or notification).

Best,
Łukasz
