### ISSUE TITLE
Webhook notifications remain in queue

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#267]
Hello, we try to upgrade to v5 module but in last version Webhook Notifications remain in queue and orders remain in progress.

Do you know what's happening?

<img width="1199" alt="Capture d’écran 2023-10-28 à 10 37 02" src="https://github.com/Adyen/adyen-prestashop/assets/92941405/a992a19a-ebb4-40a9-9167-76b18b0ce6ea">

**Comment by DamjanLogeecom** [comment]
Hello @alexandrebrubeyonds,

Thank you for reaching out to us regarding this issue,

Judging by your screenshot, we suspect the plugin’s asynchronous processes are not working as expected.

Adyen plugin performs most of its work in the background. In order to be able to detect and start background sync, the Adyen plugin simulates a long-running (background) process by asynchronously invoking background worker web requests with a minimum of 5s delay between two successive invocations.

In order to work properly with multiple asynchronous operations, the plugin needs the possibility to send a web request to itself.

To confirm this, we would like to ask you to provide us with the results of the Integration configuration validation test.

To do this, you can log into your shop and access the Adyen module. After this, you can navigate to the General Settings page and see additional links appearing in the bottom left corner. Access ‘'System Information’' page and under ‘'Integration configuration validation’' section, click on ‘'Validate’' button

Please download the reporter and share its content with us.

Kind regards.

**Comment by alexandrebrubeyonds** [comment]
Hello @DamjanLogeecom, 

Thank you for your reply.
Yes, we have a problem with this background task, the test failed.
Here is the report attached.

[auto-test-logs.json](https://github.com/Adyen/adyen-prestashop/files/13203949/auto-test-logs.json)
![Capture d’écran 2023-10-30 à 11 19 01](https://github.com/Adyen/adyen-prestashop/assets/92941405/30abf349-a21f-4dfc-b6d4-e2c44c7ce06a)

King regards,

**Comment by DamjanLogeecom** [comment]
Hello @alexandrebrubeyonds,

From the log file you shared, we can notice the following error message:

Async process failed. ERROR: 403 Message: <html><body><h1>403 Forbidden<\/h1>\nRequest forbidden by administrative rules.\n<\/body><\/html>\n

Which confirms our doubts from our first response. It seems that the Async Process is failing due to the shop’s  server configuration blocking requests sent from the plugin to itself.

In order to work properly with multiple asynchronous operations, the plugin needs the possibility to send a web request to itself (https://[SHOP-URL]/AdyenAsyncProcess)

We would advise you to check your server’s configuration and configure the server so the plugin would be able to send requests to itself.

If you have any further issues or concerns, please let us know. We will gladly assist.

Kind regards.

**Comment by alexandrebrubeyonds** [comment]
Hello @DamjanLogeecom,

Thank you for your feedback, we were able to discuss it with our system team host.

In fact, you are using a user-agent blocked by our services: **Chrome/64.0.3282.186**
They notice that the service also uses multiple IPs. They therefore temporarily accepted the user-agent Chrome/64.0.3282.186.

To advance :
- You must modify your user-agent to meet the RFC standard. A user agent must be configured for the service specifically. Using a user agent from another service (a browser, a telephone) is not recommended, precisely to avoid falling into blacklists. Defining a service-specific user agent conforming to the spec is recommended: [https://www.rfc-editor.org/rfc/rfc7231#section-5.5.3](https://www.rfc-editor.org/rfc/rfc7231#section-5.5.3)
- If you cannot do this, we need a list of IP addresses to whitelist to continue to protect the service against bad-bots using this type of problematic user-agent.

**Comment by DamjanLogeecom** [comment]
Hello @alexandrebrubeyonds,

Thank you for your feedback regarding user-agent, we will consider this change for our future releases.

As we mentioned in our previous response: “In order to work properly with multiple asynchronous operations, the plugin needs the possibility to send a web request to itself (https://[SHOP-URL]/AdyenAsyncProcess)”

Based on this, the list of IP addresses will actually match your shop web server where the module is running. The plugin sends an asynchronous web request to the same shop where it is installed.

Kind regards.

**Comment by logeecom** [comment]
Hello @alexandrebrubeyonds,

Since we got no response to our last message, we assume that the issue is resolved. Therefore, we will close this ticket.

Thank you,

Kind regards.

**Comment by alexandrebrubeyonds** [comment]
Hello,

Just for information, the problem was caused by proxy Cloudflare on DNS.
Cloudflare blocked this web request to itself.
