### ISSUE TITLE
Some invoice are empty with the adyen module

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-prestashop#270]
We have a new bug with the new Adyen module.

Some invoices are empty because order_detail don't have the id_order_invoice

[FA2000023547 1.pdf](https://github.com/Adyen/adyen-prestashop/files/13282915/FA2000023547.1.pdf)

![Capture d’écran 2023-11-07 à 16 46 18](https://github.com/Adyen/adyen-prestashop/assets/92941405/283d12d2-cb7a-4bcb-b33e-59db2313d650)

![Capture d’écran 2023-11-07 à 16 47 22](https://github.com/Adyen/adyen-prestashop/assets/92941405/730f5470-08bd-40d3-88d7-1f848c1719ca)

**Comment by DamjanLogeecom** [comment]
Hello @alexandrebrubeyonds,

Thank you for reaching out,

We have attempted to reproduce the reported issue in a local environment but without success.

Could you please provide us with the additional information listed below?

**Steps to reproduce** - Information on how to reproduce a reported issue with detailed steps.

**System version** - Prestashop system version.

**Plugin version** - Adyen plugin version installed to the integrated system.

After that, we will check all reported issues immediately and reply with feedback as soon as possible.

Best regards,
Logeecom team

**Comment by alexandrebrubeyonds** [comment]
We have this bug multiples times. 3 times in 1 week on random orders.

**Comment by logeecom** [comment]
Hello @alexandrebrubeyonds ,

In order to further investigate this issue, our team would need to log into your shop and examine the reported problem.

Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new or by sending an e-mail to [support@adyen.com](mailto:support@adyen.com). Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.

Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having.

If you have any questions or concerns, please let us know.

Kind regards.
