### ISSUE TITLE
Improvement of component version

### ISSUE THREAD

**Issue by ClementLeboeuf** [Adyen/adyen-prestashop#91]
**Is your feature request related to a problem? Please describe.**

Here are some areas for improvement available in the Drop-in version.

1 / I would like the amount of the order to be displayed in the button to confirm the order.
2 / I would also like the icons of the available credit cards CB, Visa, Mastercard, Amex ... to be displayed in the frame next to the title of the means of payment.
3 / the possibility of being able to change the wording of the means of payment available.
![CB](https://user-images.githubusercontent.com/68066683/87052403-06057c00-c201-11ea-9a3b-da9bea6c7c9b.PNG)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cyattilakiss** [comment]
Hi @ClementLeboeuf ,

Thank you for giving feedback and sending us this feature request.

"1 / I would like the amount of the order to be displayed in the button to confirm the order." -> In PrestaShop version 1.6 we create the pay button but in 1.7 Prestashop creates it. Unfortunately since we cannot add the same feature into both versions we are not going to implement this feature in the prestashop plugin.
"2 / I would also like the icons of the available credit cards CB, Visa, Mastercard, Amex ... to be displayed in the frame next to the title of the means of payment." -> this can be indeed achieved by upgrading to a newer version of the components we are using. Currently this is not prioritised but definitely on our roadmap.
"3 / the possibility of being able to change the wording of the means of payment available." -> All (or at least most) of the texts that we show can be translate therefore changed from the admin panel of your prestashop instance in the Localization/Translations page.

We are going to update this issue when we implement the latest version of the checkout component.

Best,
Attila
