### ISSUE TITLE
Change payment method order as per CA [Account->Checkout]

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-prestashop#92]
**Is your feature request related to a problem? Please describe.**
We can not change the order in which payments method are displayed. There is this option in CA under Account->Checkout but it does no effect on prestashop. Tested on TEST but not on LIVE.

**Describe the solution you'd like**
Having the same order as set up in CA.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen ,

Thank you for raising this issue with us. I've just tested it on one of our test instances and all the alternative payment methods are rendered in order. Only the card payments are "special" since it is rendered on the bottom of the page.
Is there an urgent issue related to this which can bump this enhancement's priority?

Thank you in advance.

Best
Attila
Adyen

**Comment by YanP-Adyen** [comment]
Hi @cyattilakiss sorry for the delay.
Would it be possible to include the card component is the desired order ?
At least it would be much convenient to have the cards component on top of the list.
Merchant requirement : DegriffStock

**Comment by cyattilakiss** [comment]
Hi @YanP-Adyen 

Since the version 3.0.0 the card payment order is also following the payment method orders in the CA.

best,
Attila
Adyen
